// src/components/ProgressBar.svelte
<script lang="ts">
	interface Props {
		current: number;
		total: number;
	}

	const { current, total }: Props = $props();

	const progress = $derived(Math.min(100, Math.max(0, (current / total) * 100)));
</script>

<div class="progress-text">
	{current} / {total}
</div>
<div class="progress-container">
	<div class="progress-fill" style="width: {progress}%"></div>
</div>

// src/components/ProgressBar.jsx
import React from 'react';

const ProgressBar = ({ current, total }) => {
    const progress = Math.min(100, Math.max(0, (current / total) * 100));

    return (
        <>
            <div className="progress-text">
                {current} / {total}
            </div>
            <div className="progress-container">
                <div
                    className="progress-fill"
                    style={{ width: `${progress}%` }}
                ></div>
            </div>
        </>
    );
};

export default ProgressBar;
